name: build-flashbots-images

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-prysm:
    env:
      IMAGE_NAME: initc3/flashbots-prysm
    strategy:
      matrix:
        commit: [cecd2d9cb]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image for flashbots prysm's fork
        uses: docker/build-push-action@v4
        with:
          context: .
          file: prysm/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: COMMIT=${{ matrix.commit }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.commit }},

  build-block-builder:
    env:
      IMAGE_NAME: initc3/flashbots-builder
    strategy:
      matrix:
        commit: [481f1c3c2, d3b034a29]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image for flashbots mev-boost block builder
        uses: docker/build-push-action@v4
        with:
          context: .
          file: builder/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: COMMIT=${{ matrix.commit }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.commit }},
