name: publish-flashbots-images

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-prysm:
    env:
      IMAGE_NAME: initc3/flashbots-prysm
    strategy:
      matrix:
        commit: [cecd2d9cb]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build & publish docker image for flashbots prysm's fork
        uses: docker/build-push-action@v4
        with:
          context: .
          file: prysm/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: COMMIT=${{ matrix.commit }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.COMMIT }},
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-block-builder:
    env:
      IMAGE_NAME: initc3/flashbots-builder
    strategy:
      matrix:
        commit: [481f1c3c2, d3b034a29]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build docker image for flashbots mev-boost block builder
        uses: docker/build-push-action@v4
        with:
          context: .
          file: builder/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: COMMIT=${{ matrix.commit }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.COMMIT }},
          cache-from: type=gha
          cache-to: type=gha,mode=max
